export default () => ({
  port: process.env.PORT,
  db_host: process.env.DB_HOST,
  db_user: process.env.DB_USER,
  db_name: process.env.DB_NAME,
  db_password: process.env.DB_PASSWORD,
  db_port: process.env.DB_PORT,
  jwt_secret: process.env.JWT_SECRET,
  mail_host: process.env.MAIL_HOST,
  mail_port: process.env.MAIL_PORT,
  mail_user: process.env.MAIL_USER,
  mail_password: process.env.MAIL_PASSWORD,
  default_mail_from: process.env.DEFAULT_MAIL_FROM,
  api_url: process.env.API_URL,
  client_url: process.env.CLIENT_URL,
  file_uploads_destination: process.env.FILE_UPLOADS_DESTINATION,
  photo_uploads_destination: process.env.PHOTO_UPLOADS_DESTINATION,
  google_client_id: process.env.GOOGLE_CLIENT_ID,
  google_client_secret: process.env.GOOGLE_CLIENT_SECRET,
  google_callback_url: process.env.GOOGLE_CALLBACK_URL,
  session_secret_key: process.env.SESSION_SECRET_KEY,
  client_url_google_sign_up: process.env.CLIENT_URL_GOOGLE_SIGN_UP,
  client_url_google_redirect: process.env.CLIENT_URL_GOOGLE_REDIRECT,
  jwt_expiration_time: process.env.JWT_EXPIRATION_TIME
});
